### ISSUE TITLE
New version of Microsoft.Web.Xdt nuget breaks Executable

### ISSUE THREAD

**Issue by luuksommers** [sayedihashimi/slow-cheetah.xdt#4]
The gist https://gist.github.com/sayedihashimi/f1fdc4bfba74d398ec5b breaks when executing the executable. Apperantly the version of Microsoft.Web.Xdt has been bumped a couple of months ago.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Web.XmlTransform, Version=2.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at SlowCheetah.Xdt.Program.Main(String[] args)

**Comment by sayedihashimi** [comment]
It looks like there may be an issue with the XDT task itself. I'm not really maintaining this, but you could perhaps try to get a specific version of the package which works.

**Comment by vkelman** [comment]
Why was this issue closed? The error still happens with the current Microsoft.Web.Xdt v. 3.0.0

**Comment by vkelman** [comment]
Was the functionality provided by Microsoft.Web.Xdt actually added somewhere else?
Our project always had this reference, but now I removed the reference and application compiles and seems to be working. Strange.

**Comment by obscurerichard** [comment]
I forked and fixed the gist to pin the versions of Microsoft.Web.Xdt (2.1.1) and SlowCheetah.Xdt (1.1.7-beta) so that this continues to work:

https://gist.github.com/obscurerichard/61d5173a8e60293a8513321a5fd8c994

Please update your gist - you can use the changes in my gist with or without giving credit.

**Comment by sayedihashimi** [comment]
@obscurerichard thanks, I have updated the gist at https://gist.github.com/sayedihashimi/f1fdc4bfba74d398ec5b
